# Generated by Django 4.2.3 on 2023-07-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productimage_image_categoryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
