# Generated by Django 4.2.3 on 2023-07-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slogan',
            field=models.TextField(blank=True, null=True, verbose_name='Category Slogan'),
        ),
    ]
