# Generated by Django 4.2.3 on 2023-07-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slogan',
            field=models.TextField(default='Category Description', help_text='Required', verbose_name='Category Slogan'),
        ),
    ]
